[camera]
camera_matrix = [1804.9, 0, 700.121, 0, 1800.17, 635.201, 0, 0, 1]
distort_coefficient = [-0.0886063, 0.280987, 0.00128406, -0.00286645, -0.603744]
width = 1440
height = 1080

# [calibration_info]
# rms_error = 0.0883379
# num_samples = 30

[camera.profile]
trigger_mode = false
invert_image = false
exposure_time_us = 5000  # 3ms in microseconds
gain = 16.7
rotate_angle = "Clockwise180"

[extrinsic.gimbal_yaw.gimbal_pitch]
translation = [0, 0, 0.0846902]

camera_link.translation = [0.0944955, 0, 0.0584838]

muzzle_link.translation = [0.0633901, 0, 0]
muzzle_link.roll = 0.0
# muzzle_link.pitch = 1.5
# muzzle_link.yaw = 0.2

# 偏高就+n 偏低就-n
# 压低 +n 抬高 -n
# muzzle_link.pitch = -0.25
muzzle_link.pitch = 0.0
# 第二场,偏右, -2.3 -> 0
muzzle_link.yaw = 0.0

[mcu]
mcu_authoritative_self_color = true
mcu_authoritative_bullet_speed = false
bullet_speed_default = 23.5
bullet_speed_min = 20.0
bullet_speed_max = 25.0
